swagger: "2.0"
info:
  title: your/service/v1/your_service.proto
  version: version not set
tags:
  - name: YourService
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/echo: |
    post:
        operationId: YourService_Echo
        responses:
            "200":
                description: A successful response.
                schema:
                    $ref: '#/definitions/v1StringMessage'
            default:
                description: An unexpected error response.
                schema:
                    $ref: '#/definitions/rpcStatus'
        parameters:
            - name: value
              in: query
              required: false
              type: string
        tags:
            - YourService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1StringMessage:
    type: object
    properties:
      value:
        type: string
